#端口号
server:
  port: 9999
#springCloud名
spring:
  application:
    name: gateway-service
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
#网关
zuul:
  prefix: /api
  routes:
    consumer-service: /consumer/**
    # 表示禁用所有的路由，只认我自己的路由
    ignored-services: "*"