#端口号
server:
  port: 10086
#springCloud名
spring:
  application:
    name: eureka-server
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka